development:
  adapter: postgresql
  encoding: unicode
  database: test
  host: localhost
  pool: 5
  username: postgres
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: test
  host: localhost
  pool: 5
  username: postgres
  password: 123